[package]
name = "spl-token"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "spl_token"
crate-type = [
    "cdylib",
    "lib",
]
path = "src/lib.rs"

[[test]]
name = "action"
path = "tests/action.rs"

[[test]]
name = "assert_instruction_count"
path = "tests/assert_instruction_count.rs"

[[test]]
name = "close_account"
path = "tests/close_account.rs"

[dependencies]
arrayref = "0.3.9"
bytemuck = "1.19.0"
num-derive = "0.4"
num-traits = "0.2"
num_enum ="0.7.3"
solana-program = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.5.0"
proptest = "1.5"
serial_test = "3.1.1"
#solana-program-test = { workspace = true }
solana-sdk = { workspace = true }

[features]
no-entrypoint = []
test-sbf = []

[lints.rust.unexpected_cfgs]
level = "warn"
priority = 0
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
