[package]
name = "spl-token"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
arrayref = "0.3.7"
bytemuck = "1.16.1"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.2"
solana-program = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.5.0"
proptest = "1.5"
serial_test = "3.1.1"
solana-program-test = { workspace = true}
solana-sdk = { workspace = true }

[features]
no-entrypoint = []
test-sbf = []
