[package]
name = "solana-decode-error"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "solana_decode_error"
path = "src/lib.rs"

[dependencies]
num-traits = { workspace = true }

[dev-dependencies]
num-derive = { workspace = true }
