[package]
name = "spl-token-confidential-transfer-ciphertext-arithmetic"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "spl_token_confidential_transfer_ciphertext_arithmetic"
path = "src/lib.rs"

[dependencies]
base64 = "0.22.1"
bytemuck = "1.21.0"
solana-curve25519 = { workspace = true }
solana-zk-sdk = { workspace = true }

[dev-dependencies]
curve25519-dalek = "4.1.3"
spl-token-confidential-transfer-proof-generation = { workspace = true }
