[profile.release-with-debug]
inherits = "release"
debug = true
split-debuginfo = "packed"

[workspace]
members = [
    "lang/ocpl/logger",
    "lang/ocpl/frozen-abi-macro",
    "lang/ocpl/frozen-abi",
    "lang/ocpl/sdk-macro",
    "lang/ocpl/program",
    "lang/ocpl/sdk",
    "ocios/zk-sdk",
    "ocios/curve25519",
    "ocios/zk-token-sdk",
    "ocios/compute-budget",
    "ocios/bpf",
    "ocios/type-overrides",
    "ocios/measure",
    "ocios/metrics",
    "ocios/vote",
    "ocios/program-runtime",
    "ocios/poseidon",
    "ocios/security-txt",
    "ocios/ocp/token",
    "ocios/ocp/memo",
    "ocios/ocp/program-error-derive",
    "ocios/ocp/program-error",
    "ocios/ocp/pod",
    "ocios/ocp/discriminator-syn",
    "ocios/ocp/discriminator-derive",
    "ocios/ocp/discriminator",
    "ocios/ocp/type-length-value-derive",
    "ocios/ocp/type-length-value",
    "ocios/ocp/tlv-account-resolution",
    "ocios/ocp/token-group-interface",
    "ocios/ocp/token-metadata-interface",
    "ocios/ocp/transfer-hook-interface",
    "ocios/ocp/token-2022",
    "ocios/ocp/associated-token-account",
    "ocios/ocp/instruction-padding",
    "ocios/ocp/vote",
    "ocios/ocp/zk-elgamal-proof",
    "ocios/ocp/zk-token-proof",
    "ocios/ocp/address-lookup-table",
    "ocios/ocp/bpf-loader",
    "ocios/ocp/compute-budget",
    "ocios/ocp/config",
    "ocios/ocp/loader-v4",
    "ocios/ocp/stake",
    "ocios/ocp/system",
    "ocios/version",
    "ocios/rayon-threadlimit",
    "ocios/inline-spl",
    "ocios/bucket-map",
    "ocios/vm",
    "ocios/nohash-hasher",
    "ocios/accounts-db",
    "ocios/cost-model",
    "ocios/perf",
    "ocios/account-decoder",
    "ocios/transaction-status",
    "ocios/runtime",
    "consensus/merkle-tree",
    "consensus/entry",
    "consensus/storage-proto",
    "consensus/storage-bigtable",
    "consensus/ledger",
    "consensus/poh",
    "network/net-utils",
    "network/connection-cache",
    "network/rpc-client-api",
    "network/rpc-client",
    "network/remote-wallet",
    "network/clap-utils",
    "network/rpc-client-nonce-utils",
    "network/pubsub-client",
    "network/streamer",
    "network/transaction-metrics-tracker",
    "network/quic-client",
    "network/thin-client",
    "network/tpu-client",
    "network/udp-client",
    "network/client",
    "network/bloom",
    "network/gossip",
    "access/send-transaction-service",
    "access/cli-config",
    "access/faucet",
    "access/rpc",
    "access/geyser-plugin-interface",
    "access/geyser-plugin-manager",
    "access/turbine",
    "access/chain/unified-scheduler-logic",
    "access/chain/unified-scheduler-pool",
    "access/chain/wen-restart",
    "access/chain/core",
    "node/banks-interface",
    "node/banks-server",
    "node/banks-client",
    "node/program-test",
    "node/cli-output",
    "node/test-validator",
    "node/download-utils",
    "node/genesis-utils",
    "node/validator",
    "tool/tps-client",
    "tool/cli",
    "tool/genesis",
    "tool/clap-v3-utils",
    "tool/keygen",
    "tool/zk-keygen",
    "tool/local-cluster",
    "tool/bench-tps",
    "tool/dos",
    "tool/cargo-registry",
    "tool/tokens",
]

resolver = "2"

[workspace.package]
version = "2.0.18"
authors = ["Bovey Maintainers <maintainers@solana.xyz>"]
repository = "https://github.com/nabob-labs/solana-spe"
homepage = "https://solana.xyz/"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
# On Chain Program Language
solana-logger = { path = "lang/ocpl/logger" }
solana-frozen-abi-macro = { path = "lang/ocpl/frozen-abi-macro" }
solana-frozen-abi = { path = "lang/ocpl/frozen-abi" }
solana-sdk-macro = { path = "lang/ocpl/sdk-macro" }
solana-program = { path = "lang/ocpl/program", default-features = false }
solana-sdk = { path = "lang/ocpl/sdk" }

# On Chain instruction OS
solana-zk-sdk = { path = "ocios/zk-sdk" }
solana-curve25519 = { path = "ocios/curve25519" }
solana-zk-token-sdk = { path = "ocios/zk-token-sdk" }
solana-compute-budget = { path = "ocios/compute-budget" }
solana_rbpf = { path = "ocios/bpf" }
solana-type-overrides = { path = "ocios/type-overrides" }
solana-measure = { path = "ocios/measure" }
solana-metrics = { path = "ocios/metrics" }
solana-vote = { path = "ocios/vote" }
solana-program-runtime = { path = "ocios/program-runtime" }
solana-poseidon = { path = "ocios/poseidon" }
solana-security-txt = { path = "ocios/security-txt" }
spl-token = { path = "ocios/ocp/token" }
spl-memo = { path = "ocios/ocp/memo" }
spl-program-error-derive = { path = "ocios/ocp/program-error-derive" }
spl-program-error = { path = "ocios/ocp/program-error" }
spl-pod = { path = "ocios/ocp/pod" }
spl-discriminator-syn = { path = "ocios/ocp/discriminator-syn" }
spl-discriminator-derive = { path = "ocios/ocp/discriminator-derive" }
spl-discriminator = { path = "ocios/ocp/discriminator" }
spl-type-length-value-derive = { path = "ocios/ocp/type-length-value-derive" }
spl-type-length-value = { path = "ocios/ocp/type-length-value" }
spl-tlv-account-resolution = { path = "ocios/ocp/tlv-account-resolution" }
spl-token-group-interface = { path = "ocios/ocp/token-group-interface" }
spl-token-metadata-interface = { path = "ocios/ocp/token-metadata-interface" }
spl-transfer-hook-interface = { path = "ocios/ocp/transfer-hook-interface" }
spl-token-2022 = { path = "ocios/ocp/token-2022" }
spl-associated-token-account = { path = "ocios/ocp/associated-token-account" }
spl-instruction-padding = { path = "ocios/ocp/instruction-padding" }
solana-vote-program = { path = "ocios/ocp/vote", default-features = false }
solana-zk-elgamal-proof-program = { path = "ocios/ocp/zk-elgamal-proof" }
solana-zk-token-proof-program = { path = "ocios/ocp/zk-token-proof" }
solana-address-lookup-table-program = { path = "ocios/ocp/address-lookup-table" }
solana-bpf-loader-program = { path = "ocios/ocp/bpf-loader" }
solana-compute-budget-program = { path = "ocios/ocp/compute-budget" }
solana-config-program = { path = "ocios/ocp/config" }
solana-loader-v4-program = { path = "ocios/ocp/loader-v4" }
solana-stake-program = { path = "ocios/ocp/stake" }
solana-system-program = { path = "ocios/ocp/system" }
solana-version = { path = "ocios/version" }
solana-rayon-threadlimit = { path = "ocios/rayon-threadlimit" }
solana-inline-spl = { path = "ocios/inline-spl" }
solana-bucket-map = { path = "ocios/bucket-map" }
solana-svm = { path = "ocios/vm" }
solana-nohash-hasher = { path = "ocios/nohash-hasher" }
solana-accounts-db = { path = "ocios/accounts-db" }
solana-cost-model = { path = "ocios/cost-model" }
solana-perf = { path = "ocios/perf" }
solana-account-decoder = { path = "ocios/account-decoder" }
solana-transaction-status = { path = "ocios/transaction-status" }
solana-runtime = { path = "ocios/runtime" }

# Consensus
solana-merkle-tree = { path = "consensus/merkle-tree" }
solana-entry = { path = "consensus/entry" }
solana-storage-proto = { path = "consensus/storage-proto" }
solana-storage-bigtable = { path = "consensus/storage-bigtable" }
solana-ledger = { path = "consensus/ledger" }
solana-poh = { path = "consensus/poh" }

# Network
solana-net-utils = { path = "network/net-utils" }
solana-connection-cache = { path = "network/connection-cache",default-features = false }
solana-rpc-client-api = { path = "network/rpc-client-api" }
solana-rpc-client = { path = "network/rpc-client", default-features = false }
solana-remote-wallet = { path = "network/remote-wallet", default-features = false }
solana-clap-utils = { path = "network/clap-utils" }
solana-rpc-client-nonce-utils = { path = "network/rpc-client-nonce-utils" }
solana-pubsub-client = { path = "network/pubsub-client" }
solana-streamer = { path = "network/streamer" }
solana-transaction-metrics-tracker = { path = "network/transaction-metrics-tracker" }
solana-quic-client = { path = "network/quic-client" }
solana-thin-client = { path = "network/thin-client" }
solana-tpu-client = { path = "network/tpu-client", default-features = false }
solana-udp-client = { path = "network/udp-client" }
solana-client = { path = "network/client" }
solana-bloom = { path = "network/bloom" }
solana-gossip = { path = "network/gossip" }

# Access
solana-send-transaction-service = { path = "access/send-transaction-service" }
solana-cli-config = { path = "access/cli-config" }
solana-faucet = { path = "access/faucet" }
solana-rpc = { path = "access/rpc" }
solana-geyser-plugin-interface = { path = "access/geyser-plugin-interface" }
solana-geyser-plugin-manager = { path = "access/geyser-plugin-manager" }
solana-turbine = { path = "access/turbine" }
solana-unified-scheduler-logic = { path = "access/chain/unified-scheduler-logic" }
solana-unified-scheduler-pool = { path = "access/chain/unified-scheduler-pool" }
solana-wen-restart = { path = "access/chain/wen-restart" }
solana-core = { path = "access/chain/core" }

# Node
solana-banks-interface = { path = "node/banks-interface" }
solana-banks-server = { path = "node/banks-server" }
solana-banks-client = { path = "node/banks-client" }
solana-program-test = { path = "node/program-test" }
solana-cli-output = { path = "node/cli-output" }
solana-test-validator = { path = "node/test-validator" }
solana-download-utils = { path = "node/download-utils" }
solana-genesis-utils = { path = "node/genesis-utils" }
solana-validator = { path = "node/validator" }

# Tool
solana-tps-client = { path = "tool/tps-client" }
solana-cli = { path = "tool/cli" }
solana-genesis = { path = "tool/genesis" }
solana-clap-v3-utils = { path = "tool/clap-v3-utils" }
solana-keygen = { path = "tool/keygen" }
solana-zk-keygen = { path = "tool/zk-keygen" }
solana-local-cluster = { path = "tool/local-cluster" }
solana-bench-tps = { path = "tool/bench-tps" }
solana-dos = { path = "tool/dos" }
solana-cargo-registry = { path = "tool/cargo-registry" }
solana-tokens = { path = "tool/tokens" }

Inflector = "0.11.4"
aquamarine = "0.3.3"
aes-gcm-siv = "0.11.1"
ahash = "0.8.10"
anyhow = "1.0.82"
arbitrary = "1.3.2"
ark-bn254 = "0.4.0"
ark-ec = "0.4.0"
ark-ff = "0.4.0"
ark-serialize = "0.4.0"
array-bytes = "=1.4.1"
arrayref = "0.3.7"
assert_cmd = "2.0"
assert_matches = "1.5.0"
async-channel = "1.9.0"
async-mutex = "1.4.0"
async-trait = "0.1.80"
atty = "0.2.11"
backoff = "0.4.0"
base64 = "0.22.1"
bincode = "1.3.3"
bitflags = { version = "2.5.0" }
blake3 = "1.5.1"
borsh = { version = "1.5.1", features = ["derive", "unstable__schema"] }
bs58 = "0.5.1"
bv = "0.11.1"
byte-unit = "4.0.19"
bytecount = "0.6.8"
bytemuck = "1.16.1"
bytemuck_derive = "1.7.0"
byteorder = "1.5.0"
bytes = "1.6"
bzip2 = "0.4.4"
caps = "0.5.5"
cargo_metadata = "0.15.4"
chrono = { version = "0.4.38", default-features = false }
chrono-humanize = "0.2.3"
clap = "2.33.1"
console = "0.15.8"
console_error_panic_hook = "0.1.7"
console_log = "0.2.2"
const_format = "0.2.32"
core_affinity = "0.5.10"
criterion = "0.5.1"
criterion-stats = "0.3.0"
crossbeam-channel = "0.5.13"
csv = "1.3.0"
ctrlc = "3.4.4"
curve25519-dalek = "3.2.1"
dashmap = "5.5.3"
derivation-path = { version = "0.2.0", default-features = false }
derivative = "2.2.0"
dialoguer = "0.10.4"
digest = "0.10.7"
dir-diff = "0.3.3"
dirs-next = "2.0.0"
dlopen2 = "0.5.0"
eager = "0.1.0"
ed25519-dalek = "=1.0.1"
ed25519-dalek-bip32 = "0.2.0"
enum-iterator = "1.5.0"
env_logger = "0.9.3"
etcd-client = "0.11.1"
fast-math = "0.1"
fd-lock = "3.0.13"
flate2 = "1.0.30"
fnv = "1.0.7"
fs_extra = "1.3.0"
futures = "0.3.30"
futures-util = "0.3.29"
gag = "1.0.0"
generic-array = { version = "0.14.7", default-features = false }
gethostname = "0.2.3"
getrandom = "0.2.10"
goauth = "0.13.1"
hex = "0.4.3"
hidapi = { version = "2.6.1", default-features = false }
histogram = "0.6.9"
hmac = "0.12.1"
http = "0.2.12"
humantime = "2.0.1"
hyper = "0.14.29"
hyper-proxy = "0.9.1"
im = "15.1.0"
index_list = "0.2.11"
indexmap = "2.2.6"
indicatif = "0.17.8"
itertools = "0.12.1"
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = [
    "unprefixed_malloc_on_supported_platforms",
] }
js-sys = "0.3.69"
json5 = "0.4.1"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
lazy-lru = "0.1.2"
lazy_static = "1.4.0"
libc = "0.2.155"
libloading = "0.7.4"
libsecp256k1 = { version = "0.6.0", default-features = false, features = [
    "std",
    "static-context",
] }
light-poseidon = "0.2.0"
log = "0.4.21"
lru = "0.7.7"
lz4 = "1.25.0"
memmap2 = "0.5.10"
memoffset = "0.9"
merlin = "3"
min-max-heap = "1.3.0"
mockall = "0.11.4"
modular-bitfield = "0.11.2"
nix = "0.28.0"
num-bigint = "0.4.5"
num-derive = "0.4"
num-traits = "0.2"
num_cpus = "1.16.0"
num_enum = "0.7.2"
openssl = "0.10"
parking_lot = "0.12"
pbkdf2 = { version = "0.11.0", default-features = false }
pem = "1.1.1"
percentage = "0.1.0"
pickledb = { version = "0.5.1", default-features = false }
predicates = "2.1"
pretty-hex = "0.3.0"
prio-graph = "0.2.1"
proc-macro2 = "1.0.85"
proptest = "1.4"
prost = "0.11.9"
prost-build = "0.11.9"
prost-types = "0.11.9"
protobuf-src = "1.1.0"
qstring = "0.7.2"
qualifier_attr = { version = "0.2.2", default-features = false }
quinn = "0.10.2"
quinn-proto = "0.10.6"
quote = "1.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.10.0"
reed-solomon-erasure = "6.0.0"
regex = "1.10.5"
reqwest = { version = "0.11.27", default-features = false }
reqwest-middleware = "0.2.5"
rolling-file = "0.2.0"
rpassword = "7.3"
rustc_version = "0.4"
rustls = { version = "0.21.12", default-features = false, features = ["quic"] }
rustversion = "1.0.17"
scopeguard = "1.2.0"
semver = "1.0.23"
seqlock = "0.2.0"
serde = "1.0.203" # must match the serde_derive version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_bytes = "0.11.14"
serde_derive = "1.0.203" # must match the serde version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_json = "1.0.117"
serde_with = { version = "2.3.3", default-features = false }
serde_yaml = "0.9.34"
serial_test = "2.0.0"
sha2 = "0.10.8"
sha3 = "0.10.8"
shuttle = "0.7.1"
signal-hook = "0.3.17"
siphasher = "0.3.11"
smallvec = "1.13.2"
smpl_jwt = "0.7.1"
socket2 = "0.5.7"
soketto = "0.7"
static_assertions = "1.1.0"
stream-cancel = "0.8.2"
strum = "0.24"
strum_macros = "0.24"
subtle = "2.5.0"
symlink = "0.1.0"
syn = "2.0"
sys-info = "0.9.1"
sysctl = "0.4.6"
systemstat = "0.2.3"
tar = "0.4.41"
tarpc = "0.29.0"
tempfile = "3.10.1"
test-case = "3.3.1"
thiserror = "1.0.61"
tiny-bip39 = "0.8.2"
# Update solana-tokio patch below when updating this version
tokio = "1.29.1"
tokio-serde = "0.8"
tokio-stream = "0.1.15"
tokio-tungstenite = "0.20.1"
tokio-util = "0.7"
toml = "0.8.12"
tonic = "0.9.2"
tonic-build = "0.9.2"
trees = "0.4.2"
tungstenite = "0.20.1"
uriparse = "0.6.4"
url = "2.5.2"
vec_extract_if_polyfill = "0.1.0"
wasm-bindgen = "0.2"
winapi = "0.3.8"
winreg = "0.50"
x509-parser = "0.14.0"
# See "zeroize versioning issues" below if you are updating this version.
zeroize = { version = "1.3", default-features = false }
zstd = "0.11.2"

[patch.crates-io]
# for details, see https://github.com/anza-xyz/crossbeam/commit/fd279d707025f0e60951e429bf778b4813d1b6bf
crossbeam-epoch = { git = "https://github.com/anza-xyz/crossbeam", rev = "fd279d707025f0e60951e429bf778b4813d1b6bf" }

[patch.crates-io.curve25519-dalek]
git = "https://github.com/anza-xyz/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"

[patch.crates-io.tokio]
git = "https://github.com/anza-xyz/solana-tokio.git"
rev = "7cf47705faacf7bf0e43e4131a5377b3291fce21"
