[package]
name = "spl-instruction-padding"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
no-entrypoint = []
test-sbf = []

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "spl_instruction_padding"
crate-type = [
    "cdylib",
    "lib",
]
path = "src/lib.rs"

[[test]]
name = "noop"
path = "tests/noop.rs"

[[test]]
name = "system"
path = "tests/system.rs"

[dependencies]
num_enum = "0.7.3"
solana-account-info = { workspace = true }
solana-cpi = { workspace = true }
solana-instruction = { workspace = true, features = ["std"] }
solana-program-entrypoint = { workspace = true }
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true }

[dev-dependencies]
solana-program = { workspace = true }
#solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
static_assertions = "1.1.0"

[lints]
workspace = true
