[package]
name = "spl-instruction-padding"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
num_enum = "0.7.2"
solana-program = { workspace = true }

[dev-dependencies]
#solana-program-test = { workspace = true }
solana-sdk = { workspace = true }

[features]
no-entrypoint = []
test-sbf = []
