[package]
name = "solana-seed-phrase"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_seed_phrase"
path = "src/lib.rs"

[dependencies]
hmac = { workspace = true }
pbkdf2 = { workspace = true }
sha2 = { workspace = true }
