[package]
name = "spl-associated-token-account"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
assert_matches = "1.5.0"
borsh= "1.5.1"
num-derive = "0.4"
num-traits = "0.2"
solana-program = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
thiserror = { workspace = true }

[features]
no-entrypoint = []
test-sbf = []
