[package]
name = "solana-precompiles"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_precompiles"
path = "src/lib.rs"

[dependencies]
lazy_static = { workspace = true }
solana-ed25519-program = { workspace = true }
solana-feature-set = { workspace = true }
solana-message = { workspace = true }
solana-precompile-error = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-secp256k1-program = { workspace = true, features = ["bincode"] }
solana-secp256r1-program = { workspace = true, default-features = false }

[features]
openssl-vendored = ["solana-secp256r1-program/openssl-vendored"]

[lints.rust.unexpected_cfgs]
level = "warn"
priority = 0
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
