[package]
name = "spl-pod"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
base64 = { version = "0.22.1",optional = true }
borsh = { version = "1.5.1", optional = true }
bytemuck = "1.16.1"
bytemuck_derive = "1.7.0"
serde = { version = "1.0.203", optional = true }
solana-program = { workspace = true }
solana-zk-token-sdk = { workspace = true }
spl-program-error = { workspace = true }

[dev-dependencies]
serde_json = "1.0.117"

[features]
borsh = ["dep:borsh"]
serde-traits = [
    "dep:serde",
    "dep:base64",
]
