[package]
name = "spl-pod"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "spl_pod"
crate-type = [
    "cdylib",
    "lib",
]
path = "src/lib.rs"

[dependencies]
borsh = { version = "1.5.1", optional = true }
bytemuck = "1.19.0"
bytemuck_derive = "1.8.0"
num-derive = "0.4"
num-traits = "0.2"
serde = { version = "1.0.214", optional = true }
solana-decode-error = { workspace = true }
solana-msg = { workspace = true }
solana-program-error = { workspace = true }
solana-program-option = { workspace = true }
solana-pubkey = { workspace = true }
solana-zk-sdk = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
base64 = "0.22.1"
serde_json = "1.0.132"

[features]
borsh = ["dep:borsh"]
serde-traits = ["dep:serde"]
