[package]
name = "spl-associated-token-account-client"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "spl_associated_token_account_client"
path = "src/lib.rs"

[dependencies]
solana-instruction = { workspace = true, features = ["std"] }
solana-pubkey = { workspace = true, features = ["curve25519"] }

[dev-dependencies]
solana-program = { workspace = true }
