[package]
name = "spl-program-error"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "spl_program_error"
crate-type = [
    "cdylib",
    "lib",
]
path = "src/lib.rs"

[[test]]
name = "bench"
path = "tests/bench.rs"

[[test]]
name = "decode"
path = "tests/decode.rs"

[[test]]
name = "into"
path = "tests/into.rs"

[[test]]
name = "mod"
path = "tests/mod.rs"

[[test]]
name = "print"
path = "tests/print.rs"

[[test]]
name = "spl"
path = "tests/spl.rs"

[dependencies]
num-derive = "0.4"
num-traits = "0.2"
solana-program = { workspace = true }
spl-program-error-derive = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.5"
serial_test = "3.1"
solana-sdk = { workspace = true }
