[package]
name = "solana-program-pack"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_program_pack"
path = "src/lib.rs"

[dependencies]
solana-program-error = { workspace = true }
