[package]
name = "solana-nonce-account"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_nonce_account"
path = "src/lib.rs"

[dependencies]
solana-account = { workspace = true, features = ["bincode"] }
solana-hash = { workspace = true }
solana-nonce = { workspace = true, features = ["serde"] }
solana-sdk-ids = { workspace = true }

[dev-dependencies]
solana-fee-calculator = { workspace = true }
solana-pubkey = { workspace = true }
