[package]
name = "solana-slot-history"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_slot_history"
path = "src/lib.rs"

[dependencies]
bv = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-sdk-ids = { workspace = true, optional = true }
solana-sysvar-id = { workspace = true, optional = true }

[features]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "bv/serde",
]
sysvar = [
    "dep:solana-sdk-ids",
    "dep:solana-sysvar-id",
]
