[package]
name = "solana-precompile-error"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_precompile_error"
path = "src/lib.rs"

[dependencies]
num-traits = { workspace = true }
solana-decode-error = { workspace = true }
