[package]
name = "solana-secp256r1-program"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_secp256r1_program"
path = "src/lib.rs"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
solana-feature-set = { workspace = true }
solana-precompile-error = { workspace = true }
solana-sdk-ids = { workspace = true }

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "solana")))'.dependencies]
solana-instruction = { workspace = true, features = ["std"] }
openssl = { workspace = true }

[dev-dependencies]
solana-logger = { workspace = true }
#solana-sdk = { path = "../../sdk" }

[features]
default = []
openssl-vendored = ["openssl/vendored"]

[lints.rust.unexpected_cfgs]
level = "warn"
priority = 0
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
