[package]
name = "solana-stable-layout"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
solana-instruction = { workspace = true, default-features = false, features = [
    "std",
] }
solana-pubkey = { workspace = true, default-features = false }

[dev-dependencies]
memoffset = { workspace = true }
