[package]
name = "spl-token-confidential-transfer-proof-generation"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "spl_token_confidential_transfer_proof_generation"
path = "src/lib.rs"

[dependencies]
curve25519-dalek = "4.1.3"
solana-zk-sdk = { workspace = true }
thiserror = "2.0.11"

[lints.rust.unexpected_cfgs]
level = "warn"
priority = 0
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
