[package]
name = "solana-offchain-message"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_offchain_message"
path = "src/lib.rs"

[dependencies]
num_enum = { workspace = true }
solana-hash = { workspace = true }
solana-packet = { workspace = true }
solana-pubkey = { workspace = true, optional = true }
solana-sanitize = { workspace = true }
solana-sha256-hasher = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }

[dev-dependencies]
solana-keypair = { workspace = true }
solana-offchain-message = { path = ".", features = ["dev-context-only-utils"] }
static_assertions = { workspace = true }

[features]
dev-context-only-utils = ["verify"]
verify = [
    "dep:solana-pubkey",
    "solana-signature/verify",
]
