[package]
name = "spl-discriminator-derive"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
spl-discriminator-syn = { workspace = true }
syn = { version = "2.0", features = ["full"] }
