[package]
name = "spl-type-length-value"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "spl_type_length_value"
crate-type = [
    "cdylib",
    "lib",
]
path = "src/lib.rs"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
solana-account-info = { workspace = true }
solana-decode-error = { workspace = true }
solana-msg = { workspace = true }
solana-program-error = { workspace = true }
spl-discriminator = { workspace = true }
spl-pod = { workspace = true }
spl-type-length-value-derive = { workspace = true, optional = true }
thiserror = "1.0"

[features]
derive = ["dep:spl-type-length-value-derive"]
