[package]
name = "spl-memo"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "spl_memo"
crate-type = [
    "cdylib",
    "lib",
]
path = "src/lib.rs"

[[test]]
name = "functional"
path = "tests/functional.rs"

[dependencies]
solana-account-info = { workspace = true }
solana-instruction = { workspace = true }
solana-msg = { workspace = true }
solana-program-entrypoint = { workspace = true }
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true }

[dev-dependencies]
#solana-program-test = { workspace = true }
solana-sdk = { workspace = true }

[features]
no-entrypoint = []
test-sbf = []
