[package]
name = "spl-transfer-hook-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
arrayref = "0.3.7"
bytemuck = { version = "1.16.1", features = ["derive"] }
solana-program = { workspace = true }
spl-discriminator = { workspace = true }
spl-pod = { workspace = true }
spl-program-error = { workspace = true }
spl-tlv-account-resolution = { workspace = true}
spl-type-length-value = { workspace = true }

[dev-dependencies]
tokio = { version = "1.38.0", features = ["full"] }
