[package]
name = "spl-token-metadata-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
borsh = "1.5.1"
serde = { version = "1.0.203", optional = true }
solana-program = { workspace = true }
spl-discriminator = { workspace = true }
spl-pod = { workspace = true, features = ["borsh"] }
spl-program-error = { workspace = true }
spl-type-length-value = { workspace = true }

[dev-dependencies]
serde_json = "1.0.117"

[features]
serde-traits = [
    "dep:serde",
    "spl-pod/serde-traits",
]
