[package]
name = "spl-token-2022"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
arrayref = "0.3.7"
base64 = { version = "0.22.1", optional = true }
bytemuck = { version = "1.16.1", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.2"
serde = { version = "1.0.203", optional = true }
serde_with = { version = "3.8.1", optional = true }
solana-program = { workspace = true }
solana-security-txt = { workspace = true }
solana-zk-token-sdk = { workspace = true }
spl-memo = { workspace = true, features = ["no-entrypoint"] }
spl-pod = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-group-interface = { workspace = true }
spl-token-metadata-interface = { workspace = true }
spl-transfer-hook-interface = { workspace = true }
spl-type-length-value = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
lazy_static = "1.5.0"
proptest = "1.5"
serde_json = "1.0.117"
serial_test = "3.1.1"
#solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
spl-tlv-account-resolution = { workspace = true }

[features]
confidential-hook = []
default = [
    "confidential-hook",
    "token-group",
    "zk-ops",
]
no-entrypoint = []
serde-traits = [
    "dep:serde",
    "dep:serde_with",
    "dep:base64",
    "spl-pod/serde-traits",
]
test-sbf = []
token-group = []
zk-ops = []
