[package]
name = "spl-token-confidential-transfer-proof-extraction"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "spl_token_confidential_transfer_proof_extraction"
path = "src/lib.rs"

[dependencies]
bytemuck = "1.21.0"
solana-curve25519 = { workspace = true }
solana-program = { workspace = true }
solana-zk-sdk = { workspace = true }
spl-pod = { workspace = true }
thiserror = "2.0.11"
