[package]
name = "solana-serialize-utils"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_serialize_utils"
path = "src/lib.rs"

[dependencies]
solana-instruction = { workspace = true, default-features = false, features = [
    "std",
] }
solana-pubkey = { workspace = true, default-features = false }
solana-sanitize = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
borsh = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
solana-pubkey = { workspace = true, default-features = false, features = [
    "borsh",
    "serde",
] }
