[package]
name = "solana-feature-gate-client"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "solana_feature_gate_client"
path = "src/lib.rs"

[dependencies]
borsh = "^0.10"
num-derive = "0.4"
num-traits = "^0.2"
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_with = { version = "^3.0", optional = true }
solana-program = { workspace = true }
thiserror = "^2.0"

[dev-dependencies]

[features]
serde = [
    "dep:serde",
    "dep:serde_with",
]
test-sbf = []
