[package]
name = "solana-slot-hashes"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_slot_hashes"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-hash = { workspace = true, default-features = false }
solana-sdk-ids = { workspace = true, optional = true }
solana-sysvar-id = { workspace = true, optional = true }

[dev-dependencies]
solana-sha256-hasher = { workspace = true }

[features]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "solana-hash/serde",
]
sysvar = [
    "dep:solana-sdk-ids",
    "dep:solana-sysvar-id",
]
