[package]
name = "solana-sdk-macro"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_sdk_macro"
path = "src/lib.rs"
proc-macro = true

[dependencies]
bs58 = { workspace = true, features = ["alloc"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }
