[package]
name = "solana-seed-derivable"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_seed_derivable"
path = "src/lib.rs"

[dependencies]
solana-derivation-path = { workspace = true }
