[package]
name = "spl-discriminator"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
borsh = { version = "1", optional = true }
bytemuck = { version = "1.16.1", features = ["derive"] }
solana-program = { workspace = true }
spl-discriminator-derive = { workspace = true }

[features]
borsh = ["dep:borsh"]
