[package]
name = "spl-token-group-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
bytemuck = "1.16.1"
solana-program = { workspace = true }
spl-discriminator = { workspace = true }
spl-pod = { workspace = true, features = ["borsh"] }
spl-program-error = { workspace = true }

[dev-dependencies]
spl-type-length-value = { workspace = true, features = ["derive"] }
