[package]
name = "spl-token-group-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "spl_token_group_interface"
crate-type = [
    "cdylib",
    "lib",
]
path = "src/lib.rs"

[dependencies]
bytemuck = "1.19.0"
num-derive = "0.4"
num-traits = "0.2"
solana-decode-error = { workspace = true }
solana-instruction = { workspace = true }
solana-msg = { workspace = true }
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true }
spl-discriminator = { workspace = true }
spl-pod = { workspace = true, features = ["borsh"] }
thiserror = "1.0"

[dev-dependencies]
solana-sha256-hasher = { workspace = true }
spl-type-length-value = { workspace = true, features = ["derive"] }
