[package]
name = "spl-tlv-account-resolution"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = [
    "cdylib",
    "lib",
]

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
serde = { version = "1.0.203", optional = true }
solana-program = { workspace = true }
spl-discriminator = { workspace = true }
spl-pod = { workspace = true }
spl-program-error = { workspace = true }
spl-type-length-value = { workspace = true }

[dev-dependencies]
futures = "0.3.30"
futures-util = "0.3"
#solana-client = { workspace = true }
#solana-program-test = { workspace = true }
solana-sdk = { workspace = true }

[features]
serde-traits = ["dep:serde"]
test-sbf = []
