[package]
name = "solana-stake-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.solana]
program-id = "Stake11111111111111111111111111111111111111"

[lib]
name = "solana_stake_interface"
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]
borsh = { version = "1.5.1", features = ["derive", "unstable__schema"], optional = true }
borsh0-10 = { package = "borsh", version = "0.10.3", optional = true }
num-traits = "0.2"
serde = { version = "1.0.210", optional = true }
serde_derive = { version = "1.0.210", optional = true }
solana-decode-error = { workspace = true }
solana-clock = { workspace = true }
solana-cpi = { workspace = true, optional = true }
solana-frozen-abi = { workspace = true, features = ["frozen-abi"], optional = true }
solana-frozen-abi-macro = { workspace = true, features = ["frozen-abi"], optional = true }
solana-instruction = { workspace = true }
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true, default-features = false }
solana-system-interface = { workspace = true }
solana-sysvar-id = { workspace = true }

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
#solana-account = { workspace = true, features = ["bincode"] }
solana-borsh = { workspace = true }
#solana-program = { workspace = true, default-features = false }
static_assertions = "1.1.0"
strum = "0.24"
strum_macros = "0.24"
test-case = "3.3.1"

[features]
bincode = [
    "dep:solana-cpi",
    "solana-instruction/bincode",
    "solana-instruction/serde",
    "solana-system-interface/bincode",
    "serde",
]
borsh = [
    "dep:borsh",
    "dep:borsh0-10",
    "solana-instruction/borsh",
    "solana-program-error/borsh",
    "solana-pubkey/borsh",
]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-instruction/frozen-abi",
    "solana-pubkey/frozen-abi",
]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "solana-pubkey/serde",
]
