[package]
name = "solana-fee-calculator"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_fee_calculator"
path = "src/lib.rs"

[dependencies]
log = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }

[dev-dependencies]
solana-clock = { workspace = true }
solana-logger = { workspace = true }
static_assertions = { workspace = true }

[features]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
]
serde = [
    "dep:serde",
    "dep:serde_derive",
]
